feat(Adds Failsafe Exception Handler): Failsafe Exception Handler
codefriar/ApexKit pull request #102
Opened 2023-10-01 19:29 UTC by codefriar

This commit introduces a Failsafe Exception handler with Callable interface. This allows other bits of Apex kit to safely handle exceptions via logging, *if* the failsafeExceptionHandler is part of the org. if it's not... well the exceptions are silently handled.

2023-10-01 23:09 UTC, codefriar commented
@jamessimone i've exposed the full history of both the queueable context and the finalizer context. Also exposed a method to handle exceptions on a per-class basis

2023-10-02 19:49 UTC, dschach commented
@codefriar Multiple PMD violations - I will attempt to fix them

2023-10-02 19:57 UTC, dschach commented
@codefriar The PMD ruleset for deployment requires ApexDoc for all public methods. Do you want to update the violations in this PR and open a separate PR to fix for files not included in this PR?

* QueueableProcess.cls
* QueueableProcessDataProvider.cls
* QueueableProcessTests.cls
* ExampleQueueableProcessSteps

2023-10-02 20:02 UTC, dschach requested changes
Update ApexDocs as needed, please

2023-10-03 19:39 UTC, dschach requested changes

2023-10-03 19:39 UTC, dschach commented on force-app/main/default/classes/QueueableProcess/EnqueueNextQueueableProcessStep.cls
> +			QueueableProcess parentQueueable = (QueueableProcess) Type.forName(
@codefriar Looks like test is failing here

2023-10-03 23:28 UTC, dschach requested changes

2023-10-03 23:28 UTC, dschach commented on force-app/main/default/classes/queueable process/EnqueueNextQueueableProcessStep.cls
> +			QueueableProcess parentQueueable = (QueueableProcess) Type.forName(
@codefriar This is where the test has an error.

```
System.NullPointerException: Attempt to de-reference a null object                                                  
External entry point                                                                                                
Class.EnqueueNextQueueableProcessStep.handleException: line 92, column 1                                            
Class.EnqueueNextQueueableProcessStep.execute: line 82, column 1                                                    
Class.QueueableProcessTests.testFinalizerHandlesUnhandledExceptionPositiveFailsafeHandlerCalled: line 74, column 1  35

2023-10-04 15:55 UTC, dschach approved these changes

2023-10-04 15:55 UTC, merged